# Install script for directory: /home/blue/sot-devel/sot-openhrp-scripts/scripts-sot

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "/home/blue/sot-lib")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "DEBUG")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

# Install shared libraries without execute permission?
IF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  SET(CMAKE_INSTALL_SO_NO_EXE "1")
ENDIF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/hwpgpginitpart2")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/script/plugin.txt")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/script/base")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/script/coshell")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/script/dyn")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/script/dynmc")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/script/dynsmall")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/script/dynsmallpart1hrp2_10")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/script/dynsmallpart1hrp2_10_old")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/script/hwpg")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/script/hwpgpginit")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/script/hwpgpginitpart1hrp2_10")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/script/traces")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/script/dynfilessmall")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/script/dynfilessmallhrp2_10")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/script/dynfilessmallhrp2_10_old")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/script/simu")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/script/simusmall")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/script/dynfiles")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/acc")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/acchrp2_10")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/calib")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/calibhrp2_10")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/dynsmallpart2")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/dynsmallpart2hrp2_10")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/force")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/forcehrp2_10")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/forceL")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/forceLhrp2_10")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/forceSimu")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/grip")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/griphr2_10")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/handsAltitude")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/hwpginitframes")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/jointlimit")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/pgcom")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/selector")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/small")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/smallhrp2_10")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/smallmc")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/smallmchrp2_10")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/traj")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/walkreact")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/stepping")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/taskPosture")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/taskPosturehrp2_10")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/clamp-workspace")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/sothhrp2_10")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/script/collisiondetection")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/optimization" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/script/optimization/frigoSmall")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/optimization" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/optimization/frigo")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/stab" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/stab/flex")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/stab" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/stab/flexibility")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/stab" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/stab/sylvain")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/teleoperation" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/teleoperation/initConnec")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/teleoperation" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/teleoperation/initConnecPhantom")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/teleoperation" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/teleoperation/initConnecVFwave")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/teleoperation" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/teleoperation/initConnecAll")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/teleoperation" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/teleoperation/teleop")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/teleoperation" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/teleoperation/teleophrp2_10")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/teleoperation" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/teleoperation/teleopVFwave")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/teleoperation" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/teleoperation/teleopAll")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/teleoperation" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/teleoperation/data_epfl")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/teleoperation" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/teleoperation/data_tum")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/taskLearning" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/script/taskLearning/taskLearning")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/unittests" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/unittests/chrono")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/unittests" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/unittests/ik_arm")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/unittests" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/unittests/ik_arm_sensor")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/unittests" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/unittests/ik_arm_sensor_passive")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/unittests" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/unittests/ik_arm_sensor_vel")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/unittests" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/unittests/ik_com")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/unittests" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/unittests/ik_jl_arm")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/unittests" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/script/unittests/testInertia")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/unittests" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/script/unittests/chronoQr")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/walking" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/walking/walk")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/walking" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/walking/walkreact")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/walkreactrobotatcwe")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/walking" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/walking/hwpgfeettasks")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/walking" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/walking/hwpgjoints")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/walking" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/walking/hwpgjointsbscw")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/walking" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/walking/hwpgrefs")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/walking" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/walking/hwpgreact")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/walking" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/walking/hwpgjointsteleop")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/walking" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/walking/startherdt")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/walking" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/walking/teststeps")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/walking" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/walking/teststeps2")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/walking" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/walking/teststeps3")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/walking" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/scripts-sot/walking/teststeps3small")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script/walking" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/script/walking/hwpgfeettasksrel")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/script/walkreact-new")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/script/walkreact-force")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp-scripts/script/walkreact-joystick")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

