# Install script for directory: /home/blue/sot-devel/StackOfTasks/script

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "/home/blue/sot-lib")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "RELEASE")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

# Install shared libraries without execute permission?
IF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  SET(CMAKE_INSTALL_SO_NO_EXE "1")
ENDIF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/plugin.txt")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/base")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/coshell")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/dyn")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/dynmc")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/dynsmall")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/hwpg")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/hwpgpginit")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/traces")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/dynfilessmall")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/simu")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/simusmall")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/dynfiles")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/acc")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/calib")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/force")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/forceL")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/forceSimu")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/grip")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/handsAltitude")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/hwpginitframes")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/jointlimit")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/pgcom")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/selector")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/small")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/smallmc")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/traj")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/walkreact")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/stepping")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/taskPosture")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/clamp-workspace")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/collisiondetection")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/optimization" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/optimization/frigoSmall")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/optimization" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/optimization/frigo")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/stab" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/stab/flex")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/stab" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/stab/flexibility")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/stab" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/stab/sylvain")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/teleoperation" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/teleoperation/initConnec")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/teleoperation" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/teleoperation/initConnecPhantom")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/teleoperation" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/teleoperation/initConnecVFwave")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/teleoperation" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/teleoperation/initConnecAll")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/teleoperation" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/teleoperation/teleop")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/teleoperation" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/teleoperation/teleopVFwave")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/teleoperation" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/teleoperation/teleopAll")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/teleoperation" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/teleoperation/data_epfl")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/teleoperation" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/teleoperation/data_tum")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/taskLearning" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/taskLearning/taskLearning")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/unittests" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/unittests/chrono")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/unittests" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/unittests/ik_arm")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/unittests" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/unittests/ik_arm_sensor")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/unittests" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/unittests/ik_arm_sensor_passive")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/unittests" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/unittests/ik_arm_sensor_vel")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/unittests" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/unittests/ik_com")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/unittests" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/unittests/ik_jl_arm")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/unittests" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/unittests/testInertia")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/unittests" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/unittests/chronoQr")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/walking" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/walking/walk")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/walking" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/walking/walkreact")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/walkreactrobotatcwe")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/walking" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/walking/hwpgfeettasks")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/walking" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/walking/hwpgjoints")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/walking" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/walking/hwpgjointsbscw")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/walking" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/walking/hwpgrefs")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/walking" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/walking/hwpgreact")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/walking" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/walking/hwpgjointsteleop")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/walking" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/walking/teststeps")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/walking" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/walking/teststeps2")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/walking" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/walking/teststeps3")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/walking" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/walking/teststeps3small")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script/walking" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/walking/hwpgfeettasksrel")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/walkreact-new")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/walkreact-force")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/sot-lib/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/StackOfTasks/script/walkreact-joystick")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

